name: promodo_study
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.9+9

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  provider: ^6.1.1
  
  get_it: ^8.0.2
  
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  
  fl_chart: ^0.66.0
  
  audioplayers: ^5.2.1
  
  flutter_local_notifications: ^17.2.3
  
  vibration: ^2.0.0
  
  intl: ^0.19.0
  uuid: ^4.3.3
  
  home_widget: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  
  flutter_launcher_icons: ^0.13.1
  
  # integration_test:
  #   sdk: flutter
  
  mockito: ^5.4.4
  build_runner: ^2.4.6
  sqflite_common_ffi: ^2.3.0  


flutter:

  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/

flutter_launcher_icons:
  android: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#C8E6C9"
  adaptive_icon_foreground: "assets/images/app_icon.png"
